components:
  schemas:
    Legislation:
      description: Una legislacion
      type: object
      properties:
        id:
          $ref: "#/components/schemas/id"
        type:
          description: tipo de legislacion
          type: string
          example: ejemplo1
        status:
          $ref: "#/components/schemas/status"
      required:
        - type
    DeleteLegislation:
      description: legislation delete
      type: object
      properties:
        status:
          $ref: "#/components/schemas/status"
      required:
        - status